// Get All Events Constants
export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST"
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS"
export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE"


// Delete Task Events Constants
export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE"

// schedule Task Events Constants
export const SCHEDULE_EVENT_REQUEST = "SCHEDULE_EVENT_REQUEST"
export const SCHEDULE_EVENT_SUCCESS = "SCHEDULE_EVENT_SUCCESS"
export const SCHEDULE_EVENT_FAILURE = "SCHEDULE_EVENT_FAILURE"


// Get Event By Id Constants
export const GET_EVENT_BY_ID_REQUEST = "GET_EVENT_BY_ID_REQUEST"
export const GET_EVENT_BY_ID_SUCCESS = "GET_EVENT_BY_ID_SUCCESS"
export const GET_EVENT_BY_ID_FAILURE = "GET_EVENT_BY_ID_FAILURE"


// Update Event By Id Constants
export const UPDATE_EVENT_BY_ID_REQUEST = "UPDATE_EVENT_BY_ID_REQUEST"
export const UPDATE_EVENT_BY_ID_SUCCESS = "UPDATE_EVENT_BY_ID_SUCCESS"
export const UPDATE_EVENT_BY_ID_FAILURE = "UPDATE_EVENT_BY_ID_FAILURE"

export const CLEAR_ERRORS = "CLEAR_ERRORS"

